# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:16.9

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service
# This folder is cached between builds
# http://docs.gitlab.com/ee/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

variables:
  S3_BUCKET: ${BUCKET_NAME}

build:
  image: node:16.9
  stage: build
  script:
    - echo $CODEARTIFACT_AUTH_TOKEN
    - npm config set registry https://capdigiops-133000045839.d.codeartifact.eu-west-2.amazonaws.com/npm/cg-react-shared-components/
    - npm config set //capdigiops-133000045839.d.codeartifact.eu-west-2.amazonaws.com/npm/cg-react-shared-components/:always-auth true
    - npm config set //capdigiops-133000045839.d.codeartifact.eu-west-2.amazonaws.com/npm/cg-react-shared-components/:_authToken $CODEARTIFACT_AUTH_TOKEN
    - npm i
    - npm run build
  artifacts:
    paths:
      - ./dist
  only:
    refs:
      - develop
      - main

intialise-aws-token:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: .pre
  script:
    - CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain capdigiops --domain-owner 133000045839 --query authorizationToken --region eu-west-2 --output text)
    - echo "CODEARTIFACT_AUTH_TOKEN=$CODEARTIFACT_AUTH_TOKEN" >> build.env
  artifacts:
    reports:
      dotenv: build.env

.deploy:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - aws configure list
    - aws s3 sync ./dist s3://${S3_BUCKET_NAME}

deploy_s3:
  extends: .deploy
  stage: deploy
  dependencies:
    - build
  before_script:
    - export S3_BUCKET_NAME=${S3_BUCKET}
  only:
    refs:
      - main